import { HeroConfig } from '../types/game';

export const HEROES: HeroConfig[] = [
  {
    id: 'guanyu',
    name: '关羽',
    title: '美髯公·武圣',
    camp: 'shu',
    role: 'warrior',
    avatarChar: '羽',
    cost: 150,
    baseDamage: 85,
    baseRange: 130,
    baseAttackInterval: 1.1,
    description: '青龙偃月，威震华夏。高威能近战物理挥砍，附带范围顺劈伤害。',
    skillName: '青龙斩',
    skillDesc: '向目标扇形区域斩出凌厉刀气，造成260%物理伤害并降低敌人物理防御。',
    skillCooldown: 7,
    color: '#16a34a', // 蜀绿
    projectileType: 'slash',
    avatarUrl: './assets/heroes/guanyu.jpg',
    baseHp: 950,
  },
  {
    id: 'zhangfei',
    name: '张飞',
    title: '当阳桥·万人敌',
    camp: 'shu',
    role: 'warrior',
    avatarChar: '飞',
    cost: 140,
    baseDamage: 70,
    baseRange: 120,
    baseAttackInterval: 1.3,
    description: '丈八蛇矛横扫千军。高击退与强控场能力。',
    skillName: '当阳怒吼',
    skillDesc: '怒吼震慑周围所有敌兵，造成强力击退并眩晕 1.5 秒。',
    skillCooldown: 8,
    color: '#15803d',
    projectileType: 'spear',
    avatarUrl: './assets/heroes/zhangfei.jpg',
    baseHp: 1100,
  },
  {
    id: 'zhaoyun',
    name: '赵云',
    title: '常山·赵子龙',
    camp: 'shu',
    role: 'warrior',
    avatarChar: '云',
    cost: 175,
    baseDamage: 55,
    baseRange: 140,
    baseAttackInterval: 0.65, // 超快攻速
    description: '白马银枪，七进七出。攻速极快，对单体高移速敌人具备极强压制。',
    skillName: '龙胆连刺',
    skillDesc: '瞬间连刺 5 枪，每枪附加破甲与暴击效果。',
    skillCooldown: 6,
    color: '#059669',
    projectileType: 'spear',
    avatarUrl: './assets/heroes/zhaoyun.jpg',
    baseHp: 850,
  },
  {
    id: 'huangzhong',
    name: '黄忠',
    title: '老将·百步穿杨',
    camp: 'shu',
    role: 'archer',
    avatarChar: '忠',
    cost: 160,
    baseDamage: 110,
    baseRange: 260, // 超远射程
    baseAttackInterval: 1.5,
    description: '宝刀未老，穿杨贯日。超远射程物理狙杀，专注击杀远端高危敌人。',
    skillName: '落日穿云箭',
    skillDesc: '蓄力射出致命一箭，贯穿弹道上全部目标，伤害随距离递增。',
    skillCooldown: 9,
    color: '#d97706', // 琥珀黄
    projectileType: 'arrow',
    avatarUrl: './assets/heroes/huangzhong.jpg',
    baseHp: 580,
  },
  {
    id: 'zhugeliang',
    name: '诸葛亮',
    title: '卧龙·诸葛武侯',
    camp: 'shu',
    role: 'strategist',
    avatarChar: '亮',
    cost: 220,
    baseDamage: 65,
    baseRange: 200,
    baseAttackInterval: 1.2,
    description: '羽扇纶巾，智冠三军。召唤八卦雷击，击中后在敌军之间弹射链式闪电，降低敌速。',
    skillName: '八卦天雷阵',
    skillDesc: '召唤三道天雷轰鸣全场，对密集敌军造成大范围法术麻痹（移速降低60%）。',
    skillCooldown: 10,
    color: '#0284c7', // 天蓝/青白
    projectileType: 'lightning',
    avatarUrl: './assets/heroes/zhugeliang.jpg',
    baseHp: 620,
  },
  {
    id: 'zhouyu',
    name: '周瑜',
    title: '赤壁都督·美周郎',
    camp: 'wu',
    role: 'strategist',
    avatarChar: '瑜',
    cost: 200,
    baseDamage: 50,
    baseRange: 180,
    baseAttackInterval: 1.4,
    description: '雄姿英发，谈笑间樯橹灰飞烟灭。投掷赤壁烈焰，造成持续燃烧伤害（DoT）。',
    skillName: '火烧赤壁',
    skillDesc: '点燃大片地面形成火海，处于火海中的所有敌人受到巨额真实灼烧伤害。',
    skillCooldown: 8.5,
    color: '#dc2626', // 吴赤红
    projectileType: 'fireball',
    avatarUrl: './assets/heroes/zhouyu.jpg',
    baseHp: 600,
  },
  {
    id: 'caocao',
    name: '曹操',
    title: '乱世之枭雄',
    camp: 'wei',
    role: 'strategist',
    avatarChar: '操',
    cost: 240,
    baseDamage: 75,
    baseRange: 190,
    baseAttackInterval: 1.3,
    description: '宁教我负天下人！枭雄光环提升周围武将 25% 伤害，并从击杀中掠夺额外军饷。',
    skillName: '短歌行',
    skillDesc: '高唱对酒当歌，鼓舞全场所有驻防武将攻速提升 50%，持续 5 秒。',
    skillCooldown: 14,
    color: '#2563eb', // 魏蓝
    projectileType: 'slash',
    avatarUrl: './assets/heroes/caocao.jpg',
    baseHp: 780,
  },
  {
    id: 'sunshangxiang',
    name: '孙尚香',
    title: '江东·弓腰姬',
    camp: 'wu',
    role: 'archer',
    avatarChar: '香',
    cost: 130,
    baseDamage: 60,
    baseRange: 210,
    baseAttackInterval: 0.9,
    description: '巾帼不让须眉。快速连射散射箭，能同时压制多名进犯的散兵。',
    skillName: '百花缭乱',
    skillDesc: '向周围发射 8 支穿心箭，对周围敌群造成密集的物理箭雨洗礼。',
    skillCooldown: 6.5,
    color: '#ea580c',
    projectileType: 'arrow',
    avatarUrl: './assets/heroes/sunshangxiang.jpg',
    baseHp: 550,
  },
  {
    id: 'liubei',
    name: '刘备',
    title: '玄德·汉昭烈帝',
    camp: 'shu',
    role: 'support',
    avatarChar: '备',
    cost: 180,
    baseDamage: 52,
    baseRange: 175,
    baseAttackInterval: 1.2,
    description: '唯贤唯德，能服于人。仁德光环常驻提升周围武将 15% 免伤，战法仁泽全军回血提振。',
    skillName: '仁德昭天',
    skillDesc: '拔剑呼应桃园誓言，为全场在阵武将恢复 650 点生命，并削减休整倒计时 10 秒！',
    skillCooldown: 12,
    color: '#15803d', // 汉昭烈墨绿/金绿
    projectileType: 'slash',
    avatarUrl: './assets/heroes/liubei.jpg',
    baseHp: 900,
  },
  {
    id: 'huatuo',
    name: '华佗',
    title: '医圣·神医青囊',
    camp: 'qun',
    role: 'support',
    avatarChar: '佗',
    cost: 190,
    baseDamage: 38,
    baseRange: 185,
    baseAttackInterval: 1.0,
    description: '救死扶伤，扁鹊重生。普攻优先治疗射程内虚弱武将，战法布下青囊药阵回血控敌。',
    skillName: '青囊回春',
    skillDesc: '投掷青囊灵药阵，瞬间为重伤武将恢复 1000 点生命，并麻痹周围敌军 2.5 秒。',
    skillCooldown: 11,
    color: '#0d9488', // 青囊水绿
    projectileType: 'slash',
    avatarUrl: './assets/heroes/huatuo.jpg',
    baseHp: 650,
  },
];
