import { HeroConfig } from '../types/game';

export const HEROES: HeroConfig[] = [
  {
    id: 'guanyu',
    name: '关羽',
    title: '美髯公·武圣',
    camp: 'shu',
    role: 'warrior',
    avatarChar: '羽',
    cost: 150,
    baseDamage: 85,
    baseRange: 130,
    baseAttackInterval: 1.1,
    description: '青龙偃月，威震华夏。【挥砍·近战顺劈】均衡物理伤害，身先士卒具备极强生存力。',
    skillName: '青龙斩',
    skillDesc: '向目标扇形区域斩出凌厉青龙刀芒，造成 320% 单体暴击重斩与 180% 顺劈，并撕裂命中敌军 35% 物理护甲！',
    skillCooldown: 7,
    color: '#16a34a', // 蜀绿
    projectileType: 'slash',
    damageCategory: 'slash',
    avatarUrl: './assets/heroes/guanyu.jpg',
    baseHp: 950,
  },
  {
    id: 'zhangfei',
    name: '张飞',
    title: '当阳桥·万人敌',
    camp: 'shu',
    role: 'warrior',
    avatarChar: '飞',
    cost: 140,
    baseDamage: 70,
    baseRange: 120,
    baseAttackInterval: 1.3,
    description: '丈八蛇矛横扫千军。【挥砍·范围强控】体魄极强，擅长吸引敌兵反击火力。',
    skillName: '当阳怒吼',
    skillDesc: '当阳桥上怒吼震慑敌胆，对周围 200 码内所有敌军造成 1.8 倍物理震击并眩晕 2.2 秒！',
    skillCooldown: 8,
    color: '#15803d',
    projectileType: 'spear',
    damageCategory: 'slash',
    avatarUrl: './assets/heroes/zhangfei.jpg',
    baseHp: 1100,
  },
  {
    id: 'zhaoyun',
    name: '赵云',
    title: '常山·赵子龙',
    camp: 'shu',
    role: 'warrior',
    avatarChar: '云',
    cost: 175,
    baseDamage: 55,
    baseRange: 140,
    baseAttackInterval: 0.65, // 超快攻速
    description: '白马银枪，七进七出。【挥砍·疾速穿杨】超高攻速连刺，对感电目标能触发恐怖的电弧暴击海。',
    skillName: '龙胆连刺',
    skillDesc: '龙胆出鞘瞬间连刺 5 枪，每枪附加 100% 破甲与致命暴击效果。',
    skillCooldown: 6,
    color: '#059669',
    projectileType: 'spear',
    damageCategory: 'slash',
    avatarUrl: './assets/heroes/zhaoyun.jpg',
    baseHp: 850,
  },
  {
    id: 'huangzhong',
    name: '黄忠',
    title: '老将·百步穿杨',
    camp: 'shu',
    role: 'archer',
    avatarChar: '忠',
    cost: 160,
    baseDamage: 110,
    baseRange: 260, // 超远射程
    baseAttackInterval: 1.5,
    description: '宝刀未老，穿杨贯日。【穿刺·轻甲克星】超远狙杀，对西凉轻骑暴击 145%，但对重甲大盾严重刮痧（需配法术破盾）。',
    skillName: '落日穿云箭',
    skillDesc: '蓄力射出致命一箭贯穿弹道全线敌兵，伤害随距离递增，斩杀后排脆皮。',
    skillCooldown: 9,
    color: '#d97706', // 琥珀黄
    projectileType: 'arrow',
    damageCategory: 'pierce',
    avatarUrl: './assets/heroes/huangzhong.jpg',
    baseHp: 580,
  },
  {
    id: 'zhugeliang',
    name: '诸葛亮',
    title: '卧龙·诸葛武侯',
    camp: 'shu',
    role: 'strategist',
    avatarChar: '亮',
    cost: 220,
    baseDamage: 65,
    baseRange: 200,
    baseAttackInterval: 1.2,
    description: '羽扇纶巾，智冠三军。【法术·重装大盾克星】引九天神雷对大盾重甲造成 185% 破甲克制！',
    skillName: '八卦天雷阵',
    skillDesc: '引动九天玄雷轰炸全场，造成大范围减速并施加 4 秒【感电】（使物理攻击必暴击 1.5 倍并产生连锁电弧）。',
    skillCooldown: 10,
    color: '#0284c7', // 天蓝/青白
    projectileType: 'lightning',
    damageCategory: 'magic',
    avatarUrl: './assets/heroes/zhugeliang.jpg',
    baseHp: 620,
  },
  {
    id: 'zhouyu',
    name: '周瑜',
    title: '赤壁都督·美周郎',
    camp: 'wu',
    role: 'strategist',
    avatarChar: '瑜',
    cost: 200,
    baseDamage: 50,
    baseRange: 180,
    baseAttackInterval: 1.4,
    description: '雄姿英发，谈笑间樯橹灰飞烟灭。【法术·烈焰熔甲】大范围业火持续焚烧，克制重装步兵。',
    skillName: '火烧赤壁',
    skillDesc: '烈火席卷战场，除造成持续灼烧外，直接【熔甲】削减敌人 50% 护甲，为物理猛将铺平收割道路！',
    skillCooldown: 8.5,
    color: '#dc2626', // 吴赤红
    projectileType: 'fireball',
    damageCategory: 'magic',
    avatarUrl: './assets/heroes/zhouyu.jpg',
    baseHp: 600,
  },
  {
    id: 'caocao',
    name: '曹操',
    title: '乱世之枭雄',
    camp: 'wei',
    role: 'strategist',
    avatarChar: '操',
    cost: 240,
    baseDamage: 75,
    baseRange: 190,
    baseAttackInterval: 1.3,
    description: '宁教我负天下人！【挥砍·帝王战阵】常驻枭雄光环提升周围 180 码武将 20% 输出，且击杀敌人额外掠夺 2 点军饷。',
    skillName: '短歌行',
    skillDesc: '对酒当歌，人生几何！擂响战鼓使全场所有驻防名将攻速狂飙 50%，持续 6 秒。',
    skillCooldown: 14,
    color: '#2563eb', // 魏蓝
    projectileType: 'slash',
    damageCategory: 'slash',
    avatarUrl: './assets/heroes/caocao.jpg',
    baseHp: 780,
  },
  {
    id: 'sunshangxiang',
    name: '孙尚香',
    title: '江东·弓腰姬',
    camp: 'wu',
    role: 'archer',
    avatarChar: '香',
    cost: 130,
    baseDamage: 60,
    baseRange: 210,
    baseAttackInterval: 0.9,
    description: '巾帼不让须眉。【穿刺·轻甲杀手】快速连珠箭雨，专克突骑散兵；面对重盾需先借法师破甲。',
    skillName: '百花缭乱',
    skillDesc: '向周围发射 8 支连环破甲箭，对全方位敌群进行密集的穿透洗礼。',
    skillCooldown: 6.5,
    color: '#ea580c',
    projectileType: 'arrow',
    damageCategory: 'pierce',
    avatarUrl: './assets/heroes/sunshangxiang.jpg',
    baseHp: 550,
  },
  {
    id: 'liubei',
    name: '刘备',
    title: '玄德·汉昭烈帝',
    camp: 'shu',
    role: 'support',
    avatarChar: '备',
    cost: 180,
    baseDamage: 52,
    baseRange: 175,
    baseAttackInterval: 1.2,
    description: '唯贤唯德，能服于人。【挥砍·仁德光环】常驻使周围 160 码内友军受创减免 15%，全图振奋三军。',
    skillName: '仁德昭天',
    skillDesc: '拔双股剑感召天地，为全军恢复 650 点生命，并直接削减负伤武将休整倒计时 10 秒！',
    skillCooldown: 12,
    color: '#15803d', // 汉昭烈墨绿/金绿
    projectileType: 'slash',
    damageCategory: 'slash',
    avatarUrl: './assets/heroes/liubei.jpg',
    baseHp: 900,
  },
  {
    id: 'huatuo',
    name: '华佗',
    title: '医圣·神医青囊',
    camp: 'qun',
    role: 'support',
    avatarChar: '佗',
    cost: 190,
    baseDamage: 38,
    baseRange: 185,
    baseAttackInterval: 1.0,
    description: '救死扶伤，妙手回春。【辅助·战地医圣】普通攻击优先为负伤友军施针回血，是坚守防线的中流砥柱。',
    skillName: '青囊回春',
    skillDesc: '布下神级青囊药阵，为垂危重伤武将瞬间狂回 1000 生命，并施放麻沸散定身周围敌军 2.5 秒。',
    skillCooldown: 11,
    color: '#0d9488', // 青囊水绿
    projectileType: 'slash',
    damageCategory: 'slash',
    avatarUrl: './assets/heroes/huatuo.jpg',
    baseHp: 650,
  },
];
